## Hint Code -

Please note: the code below is a hint/starter snippet. Itâ€™s a good starting point to review and build on, but it is not a complete solution. To arrive at the correct answer, you must modify and extend this code.

In [2]:
#mounnt your google dirve
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# read the data,

import pandas as pd
myData = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/Assignment/Ch3/Ch3_Q9_Data_File.xlsx', sheet_name="IceCream")
myData.head(n=10)

   Income  Hours  Hot  Holiday
0     196      5    1        0
1     282      8    0        0
2     318      6    1        0
3     232      5    1        0
4     276      8    0        0
5     312      8    0        1
6     193      5    0        1
7     110      4    0        0
8     321      8    1        0
9     283      8    0        0

In [4]:
myData.Hours.mean()

np.float64(6.771428571428571)

In [5]:
myData['Hours'].mean() # Another equivalent expression

np.float64(6.771428571428571)

In [6]:
myData.groupby('Hot').Income.mean()

Hot
0    236.421053
1    324.875000
Name: Income, dtype: float64

In [7]:
#another equivalent expression
myData.groupby('Hot')['Income'].mean()

Hot
0    236.421053
1    324.875000
Name: Income, dtype: float64