In [1]:
#Mount the google drive  how to mount?
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
import pandas as pd

In [9]:
myData = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/2510/2510-MH/MH-Ch2/jaggia_ba_2025_ch02_data.xlsx", sheet_name = 'Spend')
myData

      ID OwnHome OwnCar  FoodSpend  TravelSpend
0      1     Yes    Yes    5472.43       827.40
1      2      No    Yes    9130.73       863.55
2      3      No    Yes    4450.67      1180.05
3      4      No    Yes    5020.72       755.70
4      5      No    Yes    3408.11       851.40
..   ...     ...    ...        ...          ...
495  496     Yes     No    3787.29      2058.75
496  497      No     No    6460.84      3852.90
497  498      No     No    3585.86      2251.95
498  499     Yes     No    1833.95      2000.25
499  500      No     No    6205.97      3667.50

[500 rows x 5 columns]

In [5]:
# sort the dataframe by the column OwnHome and the column OwnCar in this order.
# Descending order

sortedData = myData.sort_values(['OwnHome', 'OwnCar'], ascending = [False, False])
sortedData.head(n=10) #show the first 10 rows

      ID OwnHome OwnCar  FoodSpend  TravelSpend
0      1     Yes    Yes    5472.43       827.40
29    30     Yes    Yes    2260.17      1905.90
31    32     Yes    Yes    4070.45      2386.80
35    36     Yes    Yes    1853.53      1825.05
48    49     Yes    Yes    3757.25      1204.65
76    77     Yes    Yes    5550.56      1028.85
82    83     Yes    Yes    2044.21      1856.10
86    87     Yes    Yes    4548.61      1088.70
99   100     Yes    Yes    2082.23      1564.95
102  103     Yes    Yes    5201.34      1601.55

In [23]:
#c missing value in Home Ownership
pd.isna(myData.OwnHome)

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Name: OwnHome, Length: 500, dtype: bool

In [26]:
(pd.isna(myData.OwnHome)).sum()  #Note: OwnHome is a categorical variable, not a numerical variable
#Thus, you can use sum() for counting.

np.int64(3)

In [ ]:
# how many customers are carowners?
# You can apply sum as carowners has categorical value, Yes or No.
# If numberical values, be careful (not appropriate to use sum())

(myData.OwnCar =='Yes').sum()

In [ ]:
#How many customers are car owners but not home owners?
#Note: you have to use and opertor --> &, not or operator --> |
df2 = ((myData.OwnHome == 'No') & (myData.OwnCar == 'Yes'))
df2

0      False
1       True
2       True
3       True
4       True
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [ ]:
df2.sum()

np.int64(117)

In [ ]:
#How many customers have an annual household spending on travel greater than $xxxx
#and an annual household spending on food greater than $YYYY
#
#result_true_false = (myData.TravelSpend > XXXX) & (myData.FoodSpend > YYYYY)
#result_true_false

In [ ]:
# Get the dataframe from the true/false values

# result_data_frame = myData[ (myData.TravelSpend > XXXX) & (myData.FoodSpend > YYYY) ]
# result_data_frame

In [21]:
#Get the # of rows

# result_data_frame.shape


#or you can use: len(result_draft_frame)

# len (result_data_frame)

(6, 5)